# Generated by Django 5.1.1 on 2024-09-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default.example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
